### ISSUE TITLE
can you give some installation instructions?

### ISSUE THREAD

**Issue by jacobmc1** [Kodeman010/HexGridGen#2]
i tried importing it from the unity hub "open" projects selection and its says the unzipped folder isn't valid. and importing it from "new asset" or "new package" inside unity isnt working either. its so hard to make a hex map!

**Comment by KacperObara** [comment]
The actual folder You should try to open in Unity is "Project", then it should open as usual.

**Comment by jacobmc1** [comment]
Okay I’ve been trying to get chat gpt to do this I want to make a hex based
Skyrim-bannerlord-ck3 type game that is procedurally generated. And I’m
getting stuck at making a hex grid lmao

**Comment by jacobmc1** [comment]
Okay it’s downloading now I was trying to do the whole folder not the one
called project. Thanks bro! I’m gonna have issues marking the Ai for a
private economy but that’s part of the fun I guess

**Comment by KacperObara** [comment]
No problem, happy coding
